sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zj2214733006

  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5tP5EVUyk5gSUN661GaZ
    access-key-secret: pXORLn97nKJwF4GBf2t8O4DBXLfkbY
    bucket-name: web-skytakeaway
  redis:
    host: 47.76.161.56
    port: 6379
    password: 123456
  wechat:
    appid: wx4b34fef0d09cbae8
    secret: 04313bab837517351a4ea5a80d09a940
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php

