sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zj2214733006

  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: LTAI5tP5EVUyk5gSUN661GaZ
    access-key-secret: pXORLn97nKJwF4GBf2t8O4DBXLfkbY
    bucket-name: web-skytakeaway
  redis:
    host: 47.76.161.56
    port: 6379
    password: 123456
  wechat:
    appid: wx4b34fef0d09cbae8
    secret: 04313bab837517351a4ea5a80d09a940
